#!/bin/bash

F=$1
R=$2
OUTFILE=$3
OUTDIR=$4
PRIMERS=$5
MINL=$6
QUALF=$7
QUALR=$8

SCRIPT_DIR=$(readlink -f ${0%/*})

qsub $SCRIPT_DIR/submit_ITSpre.sh $F $R $OUTFILE $OUTDIR $PRIMERS $MINL $QUALF $QUALR $SCRIPT_DIR